services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
      - SERVICES=s3,iam,sts,sqs,sns,dynamodb,lambda,ecr,ecs,ec2
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./.localstack:/var/lib/localstack"

  app:
    build: ./app
    depends_on:
      - localstack
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ENDPOINT_URL=http://localstack:4566
      - BUCKET_NAME=test-bucket-local
      - PREFIX=images/
    volumes:
      # “EBS local”: un disco persistente montado en /data
      - app_data:/data

volumes:
  app_data:
